import type {
  EvidenceItem,
  Obligation,
  Revision,
  SourceDocument,
} from "./schema";

export const FINAL_APPROVAL_URL =
  "https://forestsclearance.nic.in/writereaddata/RO_Approved/051520251document-18.pdf";
export const AMENDMENT_URL =
  "https://forestsclearance.nic.in/writereaddata/AdditionalInformation/AddInfoSought/0_0_9114121512121IMOEFCC0000337514_1756881077629%282%29.pdf";
export const PROPOSAL_URL =
  "https://forestsclearance.nic.in/viewreport_B.aspx?pid=FP%2FKA%2FROAD%2F7440%2F2014";

export const sourceDocuments: SourceDocument[] = [
  {
    id: "final-approval-2025",
    title: "Stage-II / Final Approval",
    date: "2025-05-15",
    authority: "MoEFCC, Forest Conservation Division",
    sourceUrl: FINAL_APPROVAL_URL,
    pages: 5,
    role: "approval",
  },
  {
    id: "amendment-2025",
    title: "Amendment to Conditions 2 and 3",
    date: "2025-09-03",
    authority: "MoEFCC, Forest Conservation Division",
    sourceUrl: AMENDMENT_URL,
    pages: 2,
    role: "amendment",
  },
  {
    id: "proposal-record",
    title: "Proposal and public KML record",
    date: "2014-01-01",
    authority: "Forest Clearance portal",
    sourceUrl: PROPOSAL_URL,
    pages: 1,
    role: "proposal_record",
  },
];

const finalCitation = (page: number, clause: string) => ({
  documentId: "final-approval-2025",
  documentTitle: "Stage-II / Final Approval",
  page,
  clause,
  sourceUrl: FINAL_APPROVAL_URL,
});

const amendmentCitation = (clause: string) => ({
  documentId: "amendment-2025",
  documentTitle: "Amendment to Conditions 2 and 3",
  page: 1,
  clause,
  sourceUrl: AMENDMENT_URL,
});

const item = (
  input: Omit<Obligation, "confidence" | "reviewerState"> &
    Partial<Pick<Obligation, "confidence" | "reviewerState">>,
): Obligation => ({
  confidence: 0.96,
  reviewerState: "pending",
  ...input,
});

export const demoObligations: Obligation[] = [
  item({
    id: "final-c2",
    clause: "Condition 2",
    category: "Compensatory afforestation",
    requirement:
      "Raise compensatory afforestation over 9.54 ha of newly identified non-forest land.",
    responsibleParty: "State Forest Department",
    quantity: 9.54,
    unit: "ha",
    deadline: null,
    geography: "Newly identified non-forest land",
    citation: finalCitation(2, "3(2)"),
    status: "superseded",
    reason: "Replaced by the 3 September 2025 amendment.",
    evidenceIds: ["ev-final", "ev-amendment"],
  }),
  item({
    id: "amend-c2",
    clause: "Amended Condition 2",
    category: "Habitat conservation",
    requirement:
      "Conserve the newly identified 9.54 ha of non-forest land for natural growth and as wildlife habitat.",
    responsibleParty: "State Government",
    quantity: 9.54,
    unit: "ha",
    deadline: null,
    geography: "Newly identified non-forest land",
    citation: amendmentCitation("Condition 2"),
    status: "missing_evidence",
    reason:
      "The amendment establishes the duty; no parcel-level conservation or monitoring evidence is in the public review set.",
    evidenceIds: ["ev-amendment"],
  }),
  item({
    id: "final-c3",
    clause: "Condition 3",
    category: "Compensatory afforestation",
    requirement:
      "Raise additional compensatory afforestation over 9.40 ha of degraded forest land.",
    responsibleParty: "State Forest Department",
    quantity: 9.4,
    unit: "ha",
    deadline: null,
    geography: "Identified degraded forest land",
    citation: finalCitation(2, "3(3)"),
    status: "superseded",
    reason: "Replaced by the 3 September 2025 amendment.",
    evidenceIds: ["ev-final", "ev-amendment"],
  }),
  item({
    id: "amend-c3",
    clause: "Amended Condition 3",
    category: "Compensatory afforestation",
    requirement:
      "Raise compensatory afforestation over 9.40 ha of identified degraded forest land using funds already deposited by the user agency.",
    responsibleParty: "State Forest Department",
    quantity: 9.4,
    unit: "ha",
    deadline: "2028-05-15",
    geography: "Identified degraded forest land",
    citation: amendmentCitation("Condition 3"),
    status: "not_yet_due",
    reason:
      "The three-year establishment window runs from the final approval date; implementation evidence should be collected as work proceeds.",
    evidenceIds: ["ev-amendment"],
  }),
  item({
    id: "final-c4",
    clause: "Condition 4",
    category: "Schedule",
    requirement:
      "Raise compensatory afforestation within three years of final approval and maintain it thereafter under the approved plan.",
    responsibleParty: "State Government and User Agency",
    quantity: 3,
    unit: "years",
    deadline: "2028-05-15",
    geography: "Compensatory afforestation land",
    citation: finalCitation(2, "3(4)"),
    status: "not_yet_due",
    reason: "Deadline is deterministically calculated from 15 May 2025.",
    evidenceIds: ["ev-final"],
  }),
  item({
    id: "final-c5",
    clause: "Condition 5",
    category: "Soil and moisture",
    requirement:
      "Implement soil and moisture conservation activities on the CA land under the approved scheme.",
    responsibleParty: "State Government",
    quantity: null,
    unit: null,
    deadline: null,
    geography: "Compensatory afforestation land",
    citation: finalCitation(2, "3(5)"),
    status: "missing_evidence",
    reason: "No execution report, geotagged works, or field evidence is present.",
    evidenceIds: ["ev-final"],
  }),
  item({
    id: "final-c6-kml",
    clause: "Condition 6 (KML)",
    category: "Geospatial",
    requirement:
      "Upload correct KML files for the diverted and CA areas with requisite details on e-Green Watch before handing over forest land.",
    responsibleParty: "State Government",
    quantity: null,
    unit: null,
    deadline: "Before forest-land handover",
    geography: "Diverted and compensatory afforestation areas",
    citation: finalCitation(2, "3(6), first occurrence"),
    status: "partial",
    reason:
      "The proposal page lists KML records, but correct portal upload and the amended 9.54 ha parcel geometry are not verified here.",
    evidenceIds: ["ev-final", "ev-proposal", "ev-kml-index"],
  }),
  item({
    id: "final-c6-notify",
    clause: "Condition 6 (notification)",
    category: "Land tenure",
    requirement:
      "Notify the non-forest CA land as Protected Forest and upload the notification to PARIVESH before forest-land handover.",
    responsibleParty: "State Government and Nodal Officer",
    quantity: null,
    unit: null,
    deadline: "Before forest-land handover",
    geography: "Non-forest land proposed for CA",
    citation: finalCitation(2, "3(6), second occurrence"),
    status: "missing_evidence",
    reason: "The required notification is not included in the public review set.",
    evidenceIds: ["ev-final"],
  }),
  item({
    id: "final-c9",
    clause: "Condition 9",
    category: "Site management",
    requirement:
      "Do not establish labour camps on forest land and provide alternate fuels to avoid pressure on nearby forests.",
    responsibleParty: "State Government and User Agency",
    quantity: null,
    unit: null,
    deadline: "During works",
    geography: "Project and adjoining forest area",
    citation: finalCitation(3, "3(9)"),
    status: "expert_review",
    reason: "Requires a site-management record and field confirmation.",
    evidenceIds: ["ev-final"],
  }),
  item({
    id: "final-c10",
    clause: "Condition 10",
    category: "Boundary",
    requirement:
      "Demarcate the diverted forest boundary with four-foot RCC pillars bearing serial number, spacing, and GPS coordinates.",
    responsibleParty: "State Government and User Agency",
    quantity: 4,
    unit: "feet",
    deadline: null,
    geography: "Diverted forest-land boundary",
    citation: finalCitation(3, "3(10)"),
    status: "missing_evidence",
    reason: "No pillar register, coordinates, or geotagged photographs are present.",
    evidenceIds: ["ev-final"],
  }),
  item({
    id: "final-c11",
    clause: "Condition 11",
    category: "Change control",
    requirement:
      "Do not change the proposal layout without prior Central Government approval.",
    responsibleParty: "State Government and User Agency",
    quantity: null,
    unit: null,
    deadline: "Ongoing",
    geography: "Approved project footprint",
    citation: finalCitation(3, "3(11)"),
    status: "expert_review",
    reason: "Requires approved and as-built geometry comparison.",
    evidenceIds: ["ev-final"],
  }),
  item({
    id: "final-c12",
    clause: "Condition 12",
    category: "Permitted use",
    requirement:
      "Use the forest land only for the purpose specified in the proposal.",
    responsibleParty: "State Government and User Agency",
    quantity: null,
    unit: null,
    deadline: "Ongoing",
    geography: "Diverted forest land",
    citation: finalCitation(3, "3(12)"),
    status: "expert_review",
    reason: "Requires field or remote-sensing evidence beyond approval records.",
    evidenceIds: ["ev-final"],
  }),
  item({
    id: "final-c14",
    clause: "Condition 14",
    category: "Road access",
    requirement:
      "Use the approach road for mined-material transport, share it with nearby lease holders, and strengthen it at user-agency cost.",
    responsibleParty: "State Government and User Agency",
    quantity: null,
    unit: null,
    deadline: "During operation",
    geography: "Approved approach road",
    citation: finalCitation(3, "3(14)"),
    status: "expert_review",
    reason: "Operational use and sharing require records or field review.",
    evidenceIds: ["ev-final"],
  }),
  item({
    id: "final-c15",
    clause: "Condition 15",
    category: "Biodiversity",
    requirement: "Avoid damage to flora and fauna in the adjoining area.",
    responsibleParty: "State Government and User Agency",
    quantity: null,
    unit: null,
    deadline: "Ongoing",
    geography: "Area adjoining the diversion",
    citation: finalCitation(3, "3(15)"),
    status: "expert_review",
    reason: "Outcome assessment requires an ecological protocol and observations.",
    evidenceIds: ["ev-final"],
  }),
  item({
    id: "final-c16",
    clause: "Condition 16",
    category: "Biodiversity",
    requirement:
      "Create and maintain alternate avifauna habitat and eco-friendly artificial nests where nesting trees are cleared.",
    responsibleParty: "State Government and User Agency",
    quantity: null,
    unit: null,
    deadline: "Before and during tree clearance",
    geography: "Forest and settlements adjoining the diversion",
    citation: finalCitation(3, "3(16)"),
    status: "missing_evidence",
    reason: "No nest plan, locations, maintenance log, or monitoring evidence is present.",
    evidenceIds: ["ev-final"],
  }),
  item({
    id: "final-c17",
    clause: "Condition 17",
    category: "Trees",
    requirement:
      "Explore maximum feasible tree translocation and allow unavoidable felling only under Forest Department supervision.",
    responsibleParty: "User Agency and State Forest Department",
    quantity: null,
    unit: null,
    deadline: "Before tree felling",
    geography: "Project footprint",
    citation: finalCitation(3, "3(17)"),
    status: "missing_evidence",
    reason: "No tree inventory, translocation decision log, or supervision record is present.",
    evidenceIds: ["ev-final"],
  }),
  item({
    id: "final-c18",
    clause: "Condition 18",
    category: "Plantation",
    requirement:
      "Raise strip plantation on both sides of the road and central verge to IRC specification and maintain it for 7–10 years.",
    responsibleParty: "User Agency",
    quantity: 7,
    unit: "years minimum",
    deadline: null,
    geography: "Road edges and central verge",
    citation: finalCitation(3, "3(18)"),
    status: "missing_evidence",
    reason: "No plantation register, survival counts, or maintenance evidence is present.",
    evidenceIds: ["ev-final"],
  }),
  item({
    id: "final-c20",
    clause: "Condition 20",
    category: "Spoil management",
    requirement:
      "Keep overburden within the road width and dispose of muck at designated sites without allowing debris to roll down slopes.",
    responsibleParty: "State Government and User Agency",
    quantity: null,
    unit: null,
    deadline: "During earthworks",
    geography: "Road and designated dumping sites",
    citation: finalCitation(3, "3(20)"),
    status: "missing_evidence",
    reason: "No dumping-site plan, transport log, or slope inspection evidence is present.",
    evidenceIds: ["ev-final"],
  }),
  item({
    id: "final-c21",
    clause: "Condition 21",
    category: "Slope stability",
    requirement:
      "Provide retaining walls, breast walls, and drainage as required to stabilize slopes.",
    responsibleParty: "User Agency",
    quantity: null,
    unit: null,
    deadline: "During road works",
    geography: "Road slopes",
    citation: finalCitation(4, "3(21)"),
    status: "missing_evidence",
    reason: "No engineering completion drawings or field photographs are present.",
    evidenceIds: ["ev-final"],
  }),
  item({
    id: "final-c22",
    clause: "Condition 22",
    category: "Soil conservation",
    requirement:
      "Implement comprehensive soil-conservation measures in consultation with the State Forest Department.",
    responsibleParty: "State Government and User Agency",
    quantity: null,
    unit: null,
    deadline: "During works",
    geography: "Project area",
    citation: finalCitation(4, "3(22)"),
    status: "missing_evidence",
    reason: "No implementation plan or consultation record is present.",
    evidenceIds: ["ev-final"],
  }),
  item({
    id: "final-c23",
    clause: "Condition 23",
    category: "Forest rights",
    requirement:
      "Complete settlement of rights under the Forest Rights Act, 2006, if applicable, and submit prescribed documentary evidence.",
    responsibleParty: "State Government",
    quantity: null,
    unit: null,
    deadline: "Before diversion implementation",
    geography: "Forest land to be diverted",
    citation: finalCitation(4, "3(23)"),
    status: "expert_review",
    reason: "Applicability and documentary sufficiency require expert review.",
    evidenceIds: ["ev-final"],
  }),
  item({
    id: "final-c25",
    clause: "Condition 25",
    category: "Hydrology",
    requirement:
      "Design culverts and bridges so natural watercourses, drainage, and wildlife movement are not impeded.",
    responsibleParty: "State Government and User Agency",
    quantity: null,
    unit: null,
    deadline: "Before construction",
    geography: "Natural streams, rivers, and canals crossed by the road",
    citation: finalCitation(4, "3(25)"),
    status: "missing_evidence",
    reason: "No crossing inventory, designs, or wildlife-passage assessment is present.",
    evidenceIds: ["ev-final"],
  }),
  item({
    id: "final-c28",
    clause: "Condition 28",
    category: "Air quality",
    requirement: "Control fugitive dust with water-spraying arrangements on the road.",
    responsibleParty: "State Government and User Agency",
    quantity: null,
    unit: null,
    deadline: "During operation",
    geography: "Approach road",
    citation: finalCitation(4, "3(28)"),
    status: "missing_evidence",
    reason: "No spraying log, equipment record, or site observation is present.",
    evidenceIds: ["ev-final"],
  }),
  item({
    id: "final-c30",
    clause: "Condition 30",
    category: "Resettlement",
    requirement:
      "Implement the applicable R&R Plan before project work and monitor indicators and observable milestones.",
    responsibleParty: "State Government and User Agency",
    quantity: null,
    unit: null,
    deadline: "Before project work",
    geography: "Project-affected area",
    citation: finalCitation(4, "3(30)"),
    status: "expert_review",
    reason: "Applicability and milestone evidence are not established by the approval alone.",
    evidenceIds: ["ev-final"],
  }),
  item({
    id: "final-c35",
    clause: "Condition 35",
    category: "Reporting",
    requirement:
      "Submit an annual self-compliance report to the State Government, Regional Office, and Ministry by the end of March each year.",
    responsibleParty: "User Agency",
    quantity: 1,
    unit: "report per year",
    deadline: "31 March annually",
    geography: null,
    citation: finalCitation(4, "3(35)"),
    status: "missing_evidence",
    reason: "No annual self-compliance report is included in the public review set.",
    evidenceIds: ["ev-final"],
  }),
];

export const revisions: Revision[] = [
  {
    id: "revision-c2",
    originalObligationId: "final-c2",
    replacementObligationId: "amend-c2",
    effectiveDate: "2025-09-03",
    amendmentCitation: amendmentCitation("Condition 2"),
    rationale:
      "The 9.54 ha parcel changes from an afforestation site to land conserved for natural growth and wildlife habitat.",
  },
  {
    id: "revision-c3",
    originalObligationId: "final-c3",
    replacementObligationId: "amend-c3",
    effectiveDate: "2025-09-03",
    amendmentCitation: amendmentCitation("Condition 3"),
    rationale:
      "The 9.40 ha degraded-forest afforestation duty is restated as the operative CA condition; all other conditions remain unchanged.",
  },
];

export const evidenceItems: EvidenceItem[] = [
  {
    id: "ev-final",
    type: "approval",
    title: "May 2025 final approval",
    date: "2025-05-15",
    sourceUrl: FINAL_APPROVAL_URL,
    integrity: "Public source; URL retained; upload is not persisted.",
    note: "Establishes the approval conditions.",
  },
  {
    id: "ev-amendment",
    type: "amendment",
    title: "September 2025 amendment",
    date: "2025-09-03",
    sourceUrl: AMENDMENT_URL,
    integrity: "Public source; URL retained; upload is not persisted.",
    note: "Supersedes Conditions 2 and 3 and preserves all other conditions.",
  },
  {
    id: "ev-proposal",
    type: "proposal_record",
    title: "Public proposal metadata",
    date: "2014-01-01",
    sourceUrl: PROPOSAL_URL,
    integrity: "Portal record reviewed; applicant contact fields excluded.",
    note: "Records proposal FP/KA/ROAD/7440/2014 and 9.40 ha diversion.",
  },
  {
    id: "ev-kml-index",
    type: "spatial_record",
    title: "Portal KML index",
    date: "2014-01-01",
    sourceUrl: PROPOSAL_URL,
    integrity: "KML links are listed; geometry was not reliably retrievable during this review.",
    note: "Map shows only an approximate documented location, not a parcel polygon.",
  },
];

export const benchmark = {
  totalLabels: 24,
  reviewedByConsultant: 0,
  precision: null as number | null,
  recall: null as number | null,
  amendmentAccuracy: true,
  note:
    "The 24-item gold set is prepared for consultant review. Precision and recall remain unpublished until the consultant signs off.",
};
